.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-SUBSITUTE" "1" "August 2011" "" ""
.
.SH "NAME"
\fBgit\-subsitute\fR \- a git subsitution tool
.
.SH "SYNOPSIS"
git\-subsitute url \fIold_url\fR \fInew_url\fR
.
.SH "DESCRIPTION"
\'git\-subsitute\' is a tool to replace remote urls for multiple git repositories recursively
.
.SH "SEE ALSO"
bash(1), git(1) \fIhttp://github\.com/gosuri/git\-subsitute\fR
